#!/usr/bin/env bash

# Mattermost User Merge Tool

# Copyright (c) 2023 Maxwell Power
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

function _setFlags() {
  echo "DOCKER=1" >>/etc/os-release
  echo "DOCKER=1" >>/etc/environment
}

function _logging() {
  echo "Setup LOGGING"
  sed -i '/imklog/s/^/#/' /etc/rsyslog.conf
  ln -sf /dev/stdout /var/log/syslog
  unlink /var/log/apache2/access.log
  unlink /var/log/apache2/other_vhosts_access.log
  chown -R www-data:www-data /var/log/apache2 /var/www/html
  chmod -R 755 /var/log/apache2 /var/www/html
  echo "END: LOGGING"
}

function _httpd() {
  echo "Setting up HTTPD"
  openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
    -keyout /etc/ssl/private/ssl-cert-snakeoil.key \
    -out /etc/ssl/certs/ssl-cert-snakeoil.pem \
    -subj "/C=US/ST=Colorado/L=Denver/O=Security/OU=Production/CN=localhost" \
    -addext "subjectAltName=IP:127.0.0.1"
  a2ensite default-ssl.conf
  a2enmod ssl
  mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
  echo "END: HTTPD"
}

echo "START: Docker BUILD ..."
_setFlags
_logging
_httpd
echo "END: BUILD"
