#!/usr/bin/env bash

# Mattermost User Merge Tool

# Copyright (c) 2023 Maxwell Power
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [ "$1" = 'start' ]; then

  function _redirect_io() {
    ln -sf /proc/1/fd/0 /dev/stdin
    ln -sf /proc/1/fd/1 /dev/stdout
    ln -sf /proc/1/fd/2 /dev/stderr
  }

  function _start_system_services() {
    echo "Starting syslog ..."
    systemctl start rsyslog

    echo "Starting apache2 ..."
    systemctl start apache2

    echo "Checking Services after startup ..."

    echo "Checking syslog ..."
    systemctl status rsyslog || exit 1

    echo "Checking Apache2 ..."
    systemctl status apache2 || exit 1
  }

  echo "Starting Container"

  echo "Check Environment Variables ..."
  if [ -n "${DB_HOST}" ] && [ -n "${DB_USER}" ] && [ -n "${DB_PASSWORD}" ] && [ -n "${DB_NAME}" ]; then
    echo "Found Database Credentials"
  else
    echo "ERROR: Missing SQL Environment Variables"
    exit 1
  fi

  echo "Redirecting I/O ..."
  _redirect_io

  echo "Starting System SERVICES ..."
  _start_system_services
  echo "DONE: Starting SERVICES"

  echo "Passing container process control to HEALTHCHECK ..."
  exec docker-healthcheck
else
  exec "$@"
fi
