#!/usr/bin/env bash

# Mattermost User Merge Tool

# Copyright (c) 2023 Maxwell Power
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

function log_message() {
  local message="$1"
  echo "$(date +'%Y-%m-%dT%H:%M:%S.%6N%:z') ${HOSTNAME} HEALTHCHECK[$$]: $message"
}

function healthcheck_failed() {
  local message="$1"
  log_message "$message, EXITING"
  exit 1
}

function healthcheck() {
  pgrep -x rsyslogd >/dev/null || healthcheck_failed "SYSLOG NOT FOUND"
  pgrep -x apache2 >/dev/null || healthcheck_failed "APACHE2 NOT FOUND"
}

log_message "ONLINE"

CHECK_INTERVAL=15
OK_INTERVAL=300

counter=0
while true; do
  healthcheck
  counter=$((counter + CHECK_INTERVAL))

  if ((counter >= OK_INTERVAL)); then
    log_message "OK"
    counter=0
  fi

  sleep $CHECK_INTERVAL
done
